# Generated by Django 5.1.6 on 2025-02-21 15:25

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        ('employees', '0003_employee_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaveapprovalhistory',
            name='leave_approval',
        ),
        migrations.RemoveField(
            model_name='leaveattendancehistory',
            name='leave_attendance',
        ),
        migrations.RemoveField(
            model_name='leavenotification',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='leavenotification',
            name='leave_report',
        ),
        migrations.AlterModelOptions(
            name='leavereport',
            options={},
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('status', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Late', 'Late'), ('Leave', 'Leave')], default='Absent', max_length=10)),
                ('check_in', models.TimeField(blank=True, null=True)),
                ('check_out', models.TimeField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='employees.employee')),
            ],
        ),
        migrations.DeleteModel(
            name='ComplatedLeave',
        ),
        migrations.DeleteModel(
            name='LeaveApprovalHistory',
        ),
        migrations.DeleteModel(
            name='LeaveAttendanceHistory',
        ),
        migrations.DeleteModel(
            name='LeaveNotification',
        ),
    ]
